export const API_ENDPOINTS = Object.freeze({
  AUTH: Object.freeze({
    LOGIN: '/api/v1/auth/login',
    REGISTER: '/api/v1/auth/register',
    SEND_REGISTRATION_OTP: '/api/v1/auth/send-registration-otp',
    VERIFY_REGISTRATION_OTP: '/api/v1/auth/verify-registration-otp',
    FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
    SEND_OTP: '/api/v1/auth/send-otp',
    VERIFY_OTP: '/api/v1/auth/verify-otp',
    RESET_PASSWORD: '/api/v1/auth/reset-password',
    RESEND_OTP: '/api/v1/auth/resend-otp',
  }),
  LOOKUPS: Object.freeze({
    DEPARTMENTS: '/api/v1/lookups/departments',
    DESIGNATIONS: '/api/v1/lookups/designations',
    CITIES: '/api/v1/lookups/cities',
    TASK_STATUSES: '/api/v1/lookups/task-statuses',
    TASK_PRIORITIES: '/api/v1/lookups/task-priorities',
    TASK_TYPES: '/api/v1/lookups/task-types',
    USERS: '/api/v1/lookups/users',
  }),
  ADMIN: Object.freeze({
    DEPARTMENTS: '/api/v1/admin/departments',
    DEPARTMENT_SEARCH: '/api/v1/admin/departments/search',
    DEPARTMENT_BY_ID: (departmentId) => `/api/v1/admin/departments/${departmentId}`,
    DESIGNATIONS: '/api/v1/admin/designations',
    DESIGNATION_SEARCH: '/api/v1/admin/designations/search',
    DESIGNATION_BY_ID: (designationId) => `/api/v1/admin/designations/${designationId}`,
    USERS: '/api/v1/admin/users',
    USER_SEARCH: '/api/v1/admin/users/search',
    USER_BY_ID: (userId) => `/api/v1/admin/users/${userId}`,
    ACTIVATE_USER: (userId) => `/api/v1/admin/users/${userId}/activate`,
    DEACTIVATE_USER: (userId) => `/api/v1/admin/users/${userId}/deactivate`,
    ROLES: '/api/v1/admin/roles',
    ROLE_BY_ID: (roleId) => `/api/v1/admin/roles/${roleId}`,
    ASSIGN_ROLE: '/api/v1/admin/roles/assign',
    PROJECTS: '/api/v1/admin/projects',
    PROJECT_BY_ID: (projectId) => `/api/v1/admin/projects/${projectId}`,
    PROJECT_STATUS: (projectId) => `/api/v1/admin/projects/${projectId}/status`,
    ASSIGN_PROJECT_MANAGER: (projectId) => `/api/v1/admin/projects/${projectId}/assign-manager`,
    PENDING_APPROVALS: '/api/v1/admin/approval/pending',
  }),
  PROJECT_MANAGER: Object.freeze({
    PROJECTS: '/api/v1/pm/projects',
    PROJECT_BY_ID: (projectId) => `/api/v1/pm/projects/${projectId}`,
    PROJECT_PROGRESS: (projectId) => `/api/v1/pm/projects/${projectId}/progress`,
    PROJECT_STATS: (projectId) => `/api/v1/pm/projects/${projectId}/stats`,
    PROJECT_TASKS: (projectId) => `/api/v1/pm/projects/${projectId}/tasks`,
    PROJECT_MEMBERS: (projectId) => `/api/v1/pm/projects/${projectId}/members`,
    PROJECT_MEMBER_BY_USER_ID: (projectId, userId) => `/api/v1/pm/projects/${projectId}/members/${userId}`,
    TASK_BY_ID: (taskId) => `/api/v1/pm/tasks/${taskId}`,
    ASSIGN_TASK: (taskId) => `/api/v1/pm/tasks/${taskId}/assign`,
    TASK_PRIORITY: (taskId) => `/api/v1/pm/tasks/${taskId}/priority`,
    TASK_STATUS: (taskId) => `/api/v1/pm/tasks/${taskId}/status`,
    TASK_DUE_DATE: (taskId) => `/api/v1/pm/tasks/${taskId}/due-date`,
    TASKS: '/api/v1/pm/tasks',
    PROJECT_OVERVIEW: (projectId) => `/api/v1/pm/projects/${projectId}/overview`,
    EMPLOYEE_SUMMARY: (projectId) => `/api/v1/pm/projects/${projectId}/employee-summary`,
    PROJECT_TASKS_PENDING: (projectId) => `/api/v1/pm/projects/${projectId}/tasks/pending`,
    PROJECT_TASKS_COMPLETED: (projectId) => `/api/v1/pm/projects/${projectId}/tasks/completed`,
    PROJECT_TASKS_IN_PROGRESS: (projectId) => `/api/v1/pm/projects/${projectId}/tasks/in-progress`,
    PROJECT_TASKS_OVERDUE: (projectId) => `/api/v1/pm/projects/${projectId}/tasks/overdue`,
    PROJECT_TASKS_HIGH_PRIORITY: (projectId) => `/api/v1/pm/projects/${projectId}/tasks/high-priority`,
    PROJECT_TASK_COMPLETION_PERCENTAGE: (projectId) => `/api/v1/pm/projects/${projectId}/tasks/completion-percentage`,
  }),
  EMPLOYEE: Object.freeze({
    DASHBOARD: '/api/v1/employee/dashboard',
    PROJECTS: '/api/v1/employee/projects',
    PROJECT_BY_ID: (projectId) => `/api/v1/employee/projects/${projectId}`,
    PROJECT_PROGRESS: (projectId) => `/api/v1/employee/projects/${projectId}/progress`,
    PROJECT_MEMBERS: (projectId) => `/api/v1/employee/projects/${projectId}/members`,
    TASKS: '/api/v1/employee/tasks',
    TASK_BY_ID: (taskId) => `/api/v1/employee/tasks/${taskId}`,
    PENDING_TASKS: '/api/v1/employee/tasks/pending',
    COMPLETED_TASKS: '/api/v1/employee/tasks/completed',
    OVERDUE_TASKS: '/api/v1/employee/tasks/overdue',
    UPDATE_TASK_STATUS: (taskId) => `/api/v1/employee/tasks/${taskId}/status`,
    TASK_COMMENTS: (taskId) => `/api/v1/employee/tasks/${taskId}/comments`,
    COMMENT_BY_ID: (commentId) => `/api/v1/employee/comments/${commentId}`,
    PROFILE: '/api/v1/employee/profile',
    CHANGE_PASSWORD: '/api/v1/employee/profile/change-password',
  }),
})
