import { API_ENDPOINTS } from '../api/apiEndpoints'
import { httpClient } from '../api/httpClient'

export const adminService = Object.freeze({
  getDepartments: (params) => httpClient.get(API_ENDPOINTS.ADMIN.DEPARTMENTS, { params }).then((response) => response.data),
  searchDepartments: (params) => httpClient.get(API_ENDPOINTS.ADMIN.DEPARTMENT_SEARCH, { params }).then((response) => response.data),
  getDepartmentById: (departmentId) => httpClient.get(API_ENDPOINTS.ADMIN.DEPARTMENT_BY_ID(departmentId)).then((response) => response.data),
  createDepartment: (payload) => httpClient.post(API_ENDPOINTS.ADMIN.DEPARTMENTS, payload).then((response) => response.data),
  updateDepartment: (departmentId, payload) => httpClient.put(API_ENDPOINTS.ADMIN.DEPARTMENT_BY_ID(departmentId), payload).then((response) => response.data),
  deleteDepartment: (departmentId) => httpClient.delete(API_ENDPOINTS.ADMIN.DEPARTMENT_BY_ID(departmentId)).then((response) => response.data),
  getDesignations: (params) => httpClient.get(API_ENDPOINTS.ADMIN.DESIGNATIONS, { params }).then((response) => response.data),
  searchDesignations: (params) => httpClient.get(API_ENDPOINTS.ADMIN.DESIGNATION_SEARCH, { params }).then((response) => response.data),
  getDesignationById: (designationId) => httpClient.get(API_ENDPOINTS.ADMIN.DESIGNATION_BY_ID(designationId)).then((response) => response.data),
  createDesignation: (payload) => httpClient.post(API_ENDPOINTS.ADMIN.DESIGNATIONS, payload).then((response) => response.data),
  updateDesignation: (designationId, payload) => httpClient.put(API_ENDPOINTS.ADMIN.DESIGNATION_BY_ID(designationId), payload).then((response) => response.data),
  deleteDesignation: (designationId) => httpClient.delete(API_ENDPOINTS.ADMIN.DESIGNATION_BY_ID(designationId)).then((response) => response.data),
  getRoles: () => httpClient.get(API_ENDPOINTS.ADMIN.ROLES).then((response) => response.data),
  createRole: (payload) => httpClient.post(API_ENDPOINTS.ADMIN.ROLES, payload).then((response) => response.data),
  updateRole: (roleId, payload) => httpClient.put(API_ENDPOINTS.ADMIN.ROLE_BY_ID(roleId), payload).then((response) => response.data),
  deleteRole: (roleId) => httpClient.delete(API_ENDPOINTS.ADMIN.ROLE_BY_ID(roleId)).then((response) => response.data),
  assignRole: (payload) => httpClient.post(API_ENDPOINTS.ADMIN.ASSIGN_ROLE, payload).then((response) => response.data),
  getUsers: (params) => httpClient.get(API_ENDPOINTS.ADMIN.USERS, { params }).then((response) => response.data),
  searchUsers: (params) => httpClient.get(API_ENDPOINTS.ADMIN.USER_SEARCH, { params }).then((response) => response.data),
  getUserById: (userId) => httpClient.get(API_ENDPOINTS.ADMIN.USER_BY_ID(userId)).then((response) => response.data),
  updateUser: (userId, payload) => httpClient.put(API_ENDPOINTS.ADMIN.USER_BY_ID(userId), payload).then((response) => response.data),
  activateUser: (userId) => httpClient.put(API_ENDPOINTS.ADMIN.ACTIVATE_USER(userId)).then((response) => response.data),
  deactivateUser: (userId) => httpClient.put(API_ENDPOINTS.ADMIN.DEACTIVATE_USER(userId)).then((response) => response.data),
  deleteUser: (userId) => httpClient.delete(API_ENDPOINTS.ADMIN.USER_BY_ID(userId)).then((response) => response.data),
  getProjects: (params) => httpClient.get(API_ENDPOINTS.ADMIN.PROJECTS, { params }).then((response) => response.data),
  getProjectById: (projectId) => httpClient.get(API_ENDPOINTS.ADMIN.PROJECT_BY_ID(projectId)).then((response) => response.data),
  createProject: (payload) => httpClient.post(API_ENDPOINTS.ADMIN.PROJECTS, payload).then((response) => response.data),
  updateProject: (projectId, payload) => httpClient.put(API_ENDPOINTS.ADMIN.PROJECT_BY_ID(projectId), payload).then((response) => response.data),
  changeProjectStatus: (projectId, payload) => httpClient.put(API_ENDPOINTS.ADMIN.PROJECT_STATUS(projectId), payload).then((response) => response.data),
  assignProjectManager: (projectId, payload) => httpClient.put(API_ENDPOINTS.ADMIN.ASSIGN_PROJECT_MANAGER(projectId), payload).then((response) => response.data),
  deleteProject: (projectId) => httpClient.delete(API_ENDPOINTS.ADMIN.PROJECT_BY_ID(projectId)).then((response) => response.data),
})
