export const ROUTE_PATHS = Object.freeze({
  LOGIN: '/login',
  REGISTER: '/register',
  REGISTER_OTP: '/register-otp',
  VERIFY_REGISTRATION_OTP: '/verify-registration-otp',
  SEND_OTP: '/send-otp',
  VERIFY_OTP: '/verify-otp',
  FORGOT_PASSWORD_VERIFY: '/forgot-password-verify',
  RESEND_OTP: '/resend-otp',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '*',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_DEPARTMENTS: '/admin/departments',
  ADMIN_DESIGNATIONS: '/admin/designations',
  ADMIN_USERS: '/admin/users',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_PROJECTS: '/admin/projects',
  PM_DASHBOARD: '/pm/dashboard',
  PM_PROJECTS: '/pm/projects',
  PM_TASKS: '/pm/tasks',
  EMPLOYEE_DASHBOARD: '/employee/dashboard',
  EMPLOYEE_PROJECTS: '/employee/projects',
  EMPLOYEE_TASKS: '/employee/tasks',
  EMPLOYEE_PROFILE: '/employee/profile',
})
